import{a as w,S as b,i as l}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const B="51864768-c4389465b0331a2f70f5d6290",S="https://pixabay.com/api/";async function q(n,t=1){const a={key:B,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await w.get(S,{params:a})).data}const h={getImagesByQuery:q},p=document.querySelector(".gallery"),y=document.querySelector(".loader-box"),f=document.querySelector(".pagination-button"),v=new b(".gallery a",{captionsData:"alt",captionDelay:250});function M(n){const t=n.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:s,comments:m,downloads:L})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${a}" alt="${e}" class="gallery-image" loading="lazy"/>
        </a>
        <ul class="gallery-info">
          <li><span>Likes</span> ${o}</li>
          <li><span>Views</span> ${s}</li>
          <li><span>Comments</span> ${m}</li>
          <li><span>Downloads</span> ${L}</li>
        </ul>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),v.refresh()}function E(){p.innerHTML=""}function P(){y.classList.remove("hidden")}function R(){y.classList.add("hidden")}function $(){f.classList.remove("hidden")}function x(){f.classList.add("hidden")}const r={createGallery:M,clearGallery:E,showLoader:P,hideLoader:R,showLoadMoreButton:$,hideLoadMoreButton:x},g=document.querySelector(".form"),I=g.querySelector("input[name='search-text']"),O=document.querySelector(".pagination-button");let d="",c=1,u=0;g.addEventListener("submit",async n=>{if(n.preventDefault(),d=I.value.trim(),c=1,!d){l.warning({title:"Input required",message:"Please enter a search term!",position:"topRight"});return}r.clearGallery(),r.hideLoadMoreButton(),r.showLoader();try{const t=await h.getImagesByQuery(d,c);if(u=t.totalHits,!t.hits.length){l.error({title:"No Results",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}r.createGallery(t.hits),u>t.hits.length?r.showLoadMoreButton():l.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){l.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}finally{r.hideLoader()}});O.addEventListener("click",async()=>{c++,r.hideLoadMoreButton(),r.showLoader();try{const n=await h.getImagesByQuery(d,c);r.createGallery(n.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),c*15<u?r.showLoadMoreButton():l.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(n){console.error(n)}finally{r.hideLoader()}});
//# sourceMappingURL=index.js.map
