import{a as w,S as b,i}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const B="51864768-c4389465b0331a2f70f5d6290",S="https://pixabay.com/api/";async function q(a,t=1){const n={key:B,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await w.get(S,{params:n})).data}const h={getImagesByQuery:q},p=document.querySelector(".gallery"),g=document.querySelector(".loader-box"),y=document.querySelector(".pagination-button"),v=new b(".gallery a",{captionsData:"alt",captionDelay:250});function M(a){const t=a.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:l,comments:f,downloads:L})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${n}" alt="${e}" class="gallery-image" loading="lazy"/>
        </a>
        <ul class="gallery-info">
          <li><span>Likes</span> ${o}</li>
          <li><span>Views</span> ${l}</li>
          <li><span>Comments</span> ${f}</li>
          <li><span>Downloads</span> ${L}</li>
        </ul>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),v.refresh()}function E(){p.innerHTML=""}function P(){g.classList.remove("hidden")}function R(){g.classList.add("hidden")}function $(){y.classList.remove("hidden")}function x(){y.classList.add("hidden")}const r={createGallery:M,clearGallery:E,showLoader:P,hideLoader:R,showLoadMoreButton:$,hideLoadMoreButton:x},m=document.querySelector(".form"),I=m.querySelector("input[name='search-text']"),O=document.querySelector(".pagination-button");let d="",c=1,u=0;m.addEventListener("submit",async a=>{if(a.preventDefault(),d=I.value.trim(),c=1,!d){i.warning({title:"Input required",message:"Please enter a search term!",position:"topRight"});return}r.clearGallery(),r.hideLoadMoreButton(),r.showLoader();try{const t=await h.getImagesByQuery(d,c);if(u=t.totalHits,!t.hits.length){i.error({title:"No Results",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}r.createGallery(t.hits),u>t.hits.length?r.showLoadMoreButton():i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}finally{r.hideLoader()}});O.addEventListener("click",async()=>{c++,r.hideLoadMoreButton(),r.showLoader();try{const a=await h.getImagesByQuery(d,c);r.createGallery(a.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),c*15<u?r.showLoadMoreButton():i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Failed to load more images. Please try again later.",position:"topRight"})}finally{r.hideLoader()}});
//# sourceMappingURL=index.js.map
