import{a as w,S as b,i as d}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const B="51864768-c4389465b0331a2f70f5d6290",S="https://pixabay.com/api/";async function q(r,t=1){const a={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await w.get(S,{params:a})).data}const h={getImagesByQuery:q},y=document.querySelector(".gallery"),f=document.querySelector(".loader-box"),p=document.querySelector(".pagination-button"),v=new b(".gallery a",{captionsData:"alt",captionDelay:250});function M(r){const t=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:s,comments:m,downloads:L})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${a}" alt="${e}" class="gallery-image" loading="lazy"/>
        </a>
        <ul class="gallery-info">
          <li><span>Likes</span> ${o}</li>
          <li><span>Views</span> ${s}</li>
          <li><span>Comments</span> ${m}</li>
          <li><span>Downloads</span> ${L}</li>
        </ul>
      </li>`).join("");y.insertAdjacentHTML("beforeend",t),v.refresh()}function E(){y.innerHTML=""}function $(){f.classList.remove("hidden")}function x(){f.classList.add("hidden")}function P(){p.classList.remove("hidden")}function O(){p.classList.add("hidden")}const n={createGallery:M,clearGallery:E,showLoader:$,hideLoader:x,showLoadMoreButton:P,hideLoadMoreButton:O},g=document.querySelector(".form"),R=g.querySelector("input[name='search-text']"),G=document.querySelector(".pagination-button");let c="",l=1,u=0;g.addEventListener("submit",async r=>{if(r.preventDefault(),c=R.value.trim(),l=1,!!c){n.clearGallery(),n.hideLoadMoreButton(),n.showLoader();try{const t=await h.getImagesByQuery(c,l);if(u=t.totalHits,!t.hits.length){d.error({title:"No Results",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}n.createGallery(t.hits),u>t.hits.length&&n.showLoadMoreButton()}catch(t){d.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}finally{n.hideLoader()}}});G.addEventListener("click",async()=>{l++,n.showLoader();try{const r=await h.getImagesByQuery(c,l);n.createGallery(r.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),l*15>=u&&(n.hideLoadMoreButton(),d.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){console.error(r)}finally{n.hideLoader()}});
//# sourceMappingURL=index.js.map
